[default]
DEBUG = false
TESTING = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
JSON_AS_ASCII = false
SQLALCHEMY_BINDS = { development="sqlite:///flaskeleton.db", production="sqlite:///myproduction.db" }
DEFAULT_TENANT = "development"
ENABLE_MULTI_TENANT = true
API_PREFIX = "/flaskeleton-api"

[development]
DEBUG = true

[staging]
configs = "here"

[testing]
DEBUG = true
TESTING = true
SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
ENABLE_MULTI_TENANT = false

[production]
configs = "here"
